angular.module('myApp').factory 'authenticateService', ($rootScope, sessionService, $location) ->
  {
    login: (user) ->
      sessionService.create user
      return
    logout: ->
      sessionService.destroy()
      return
    isLogged: ->
      if sessionService.get()
        true
      else
        false

  }

# ---
# generated by js2coffee 2.2.0
