angular.module('myApp').factory 'sessionService', ($rootScope) ->
  currentUser = undefined
  {
    create: (user) ->
      currentUser = user
      #currentUser.email=user.email; 
      #currentUser.pass=user.pass;
    get: ->
      currentUser
    destroy: ->
      currentUser = null

  }

# ---
# generated by js2coffee 2.2.0
