angular.module('myApp').controller 'navController', [
  '$scope'
  '$state'
  '$location'
  'authenticateService'
  'sessionService'
  ($scope, $state, $location, authenticateService, sessionService) ->
    $scope.tabs = [
      {
        heading: 'home'
        route: 'home'
        active: true
        isVisible: 'false'
      }
      {
        heading: 'signin'
        route: 'signin'
        active: false
        isVisible: 'false'
      }
      {
        heading: 'signout'
        route: 'signout'
        active: false
        isVisible: 'false'
      }
      {
        heading: 'dashboard'
        route: 'dashboard'
        active: false
        isVisible: 'false'
      }
    ]

    $scope.tabSelected = (route) ->
      $state.go route
      return

    $scope.showMenue = (tab) ->
      if authenticateService.isLogged() == true and tab.heading == 'signin'
        false
      else if authenticateService.isLogged() == false and tab.heading == 'signout'
        false
      else if tab.heading == 'home' or tab.heading == 'dashboard'
        true
      else
        true

    return
]

# ---
# generated by js2coffee 2.2.0
