angular.module('myApp').controller 'signoutController', ($scope, $state, $location, authenticateService, sessionService) ->

  $scope.signout = ->
    authenticateService.logout()
    $location.path 'home'
    return

  return

# ---
# generated by js2coffee 2.2.0
