angular.module('myApp').controller 'signupController', ($scope, $state, $location, authenticateService, sessionService) ->

  $scope.submitClick = ->
    if $scope.userInfo.$invlid == true
      alert 'some Invlid Information'
    else
      #authenticateService.logout();
      $location.path 'signin'
    return

  $scope.isfavoritesSelected = (object) ->
    Checked = false
    angular.forEach object, (value, key) ->
      if value.checked
        Checked = true
      return
    Checked

  $scope.country = [
    {
      Id: 1
      name: 'Iran'
    }
    {
      Id: 2
      name: 'Turkey'
    }
    {
      Id: 3
      name: 'Russia'
    }
    {
      Id: 4
      name: 'China'
    }
  ]
  $scope.favorites = [
    {
      value: 1
      label: 'flight'
    }
    {
      value: 2
      label: 'hotel'
    }
    {
      value: 3
      label: 'price'
    }
  ]
  $scope.gender = [
    {
      Id: 'M'
      Text: 'Male'
    }
    {
      Id: 'F'
      Text: 'Female'
    }
    {
      Id: 'O'
      Text: 'Other'
    }
  ]

  $scope.favoriteSelected = (position, favorites) ->
    angular.forEach favorites, (item, index) ->
      if position != index
        item.checked = false
      return
    return

  return

# ---
# generated by js2coffee 2.2.0
